!------------------------------------------------------------------
! calculates derivative of prognostics wrt background
! based on util/hessinv
! FastOpt Nov 05
!------------------------------------------------------------------
PROGRAM bsens
  IMPLICIT NONE
  
  REAL, ALLOCATABLE, DIMENSION( :, :) :: hess, dpdx, d2Jdxdb, dxdb, dpdb, d2Jdxdbin
  REAL, DIMENSION(:), ALLOCATABLE :: evals, x, y, plot, mask
  REAL, DIMENSION(1000000) ::  work
  INTEGER, DIMENSION(1000000) :: lwork
  INTEGER :: nx, np, nbgr, nbgrin, i, j, k, l, info, iin, nlat, nlon, nlatin, ntime
  CHARACTER :: ifnum1
  CHARACTER*30 :: ifname
  CHARACTER*2 :: ifnum
  
! later transform file into .F90 and use Makefile macros for dimensions
  nlat = 24
  nlon = 36
  nx = 57
  np = nlon*nlat
  nlatin = 4
  nbgrin = nlon * nlatin
  nbgr = nlon*nlat
  ntime = 21*12

  ALLOCATE( hess( nx, nx), dpdx( nx, np))
  ALLOCATE( d2Jdxdb( nbgr, nx), d2Jdxdbin( nbgrin, nx))
  ALLOCATE( dxdb( nx, nbgr), dpdb( np, nbgr))
  ALLOCATE( mask(np), plot(nbgr))

! reading Hessian and Jacobian
! OPEN(unit=1,file='output/hesscol.bin',form='unformatted') !full Hessian  
  OPEN(unit=1,file='output/redhess.bin',form='unformatted') !reduced Hessian 
  READ(1) hess
  CLOSE(1)
  OPEN(unit=1,file='output/pjaccol.dat',form='unformatted')
  READ(1) dpdx
  CLOSE(1)
!  WRITE(6,*) 'i  dp(i)/dx(2) dp(i)/dx(40) dp(i)/dx(57)'
  do i = 1, np
!     print*,i,dpdx(2,i),dpdx(40,i),dpdx(57,i)
  enddo

! compose d2Jdxdb from chuncks that are read in
! some bookkeeping of filenames necessary
! is consistent with files generated by target ifwd from main Makefile
  d2Jdxdb=0.
  do iin=1,nlat,nlatin
     if (iin.lt.10) then
        write(ifnum1,'(i1)') iin
        ifname='output/d2Jdxdb-'//ifnum1//'.bin'
     else
        write(ifnum,'(i2)') iin
        ifname='output/d2Jdxdb-'//ifnum//'.bin'
     endif
     print*,'reading ',ifname
     OPEN(unit=1,file=ifname,form='unformatted')
     READ(1) d2Jdxdbin
     CLOSE(1)
     do i=1,nlon
        do j =iin,iin+nlatin-1
           k = i + (j-1)*nlon
           l = i + (j-iin)*nlon
           d2Jdxdb(k,:)=d2Jdxdbin(l,:)     
        enddo
     enddo
  enddo

! invert Hessian
  CALL syminv( hess, info)

! parameter sensitivity to background
  dxdb = - MATMUL( hess, TRANSPOSE(d2Jdxdb))

  OPEN(unit=1, file='output/dxdb.bin', form='unformatted')
  WRITE(1) dxdb
  CLOSE(1)

! prognostic sensitivity to background
  dpdb = MATMUL( TRANSPOSE(dpdx), dxdb)

! output in binary and ascii formats
  OPEN(unit=2, file='output/dpdb.bin', form='unformatted')
  WRITE(2) dpdb
  CLOSE(2)
  OPEN(unit=2, file='output/dpdb.dat', form='formatted')
  WRITE(2,*) np, nbgr
  WRITE(2,*) dpdb
  CLOSE(2)

! finally plot
! first define europa
  mask=0.
!  do i =1,nlon
!     do j=1,nlat
  do i =18,21
     do j=18,21
        k = i + (j-1)*nlon
        mask(k)=1.
     enddo
  enddo
! now mask progs with europe
  plot=0.
  do l=1,np
     plot(:)=plot(:)+mask(l)*dpdb(l,:)     
  enddo
! and plot
  OPEN(unit=2, file='output/europe.dat', form='formatted')
  WRITE(2,*) nbgr
  WRITE(2,*) plot
  print*,'writing output/europe.dat'
  CLOSE(unit=2)
! and now Southamerica
  mask=0.
!  do i =1,nlon
!     do j=1,nlat
  do i =11,15
     do j=6,14
        k = i + (j-1)*nlon
        mask(k)=1.
     enddo
  enddo
! now mask progs 
  plot=0.
  do l=1,np
     plot(:)=plot(:)+mask(l)*dpdb(l,:)     
  enddo
! and plot
  OPEN(unit=2, file='output/samerica.dat', form='formatted')
  WRITE(2,*) nbgr
  WRITE(2,*) plot
  print*,'writing output/samerica.dat'
  CLOSE(unit=2)
! and now Northamerica
  mask=0.
!  do i =1,nlon
!     do j=1,nlat
  do i =1,13
     do j=15,21
        k = i + (j-1)*nlon
        mask(k)=1.
     enddo
  enddo
! now mask progs
  plot=0.
  do l=1,np
     plot(:)=plot(:)+mask(l)*dpdb(l,:)     
  enddo
! and plot
  OPEN(unit=2, file='output/namerica.dat', form='formatted')
  WRITE(2,*) nbgr
  WRITE(2,*) plot
  print*,'writing output/namerica.dat'
  CLOSE(unit=2)
! and now the same for the global uptake
  mask=1.
  plot=0.
  do l=1,np
     plot(:)=plot(:)+mask(l)*dpdb(l,:)     
  enddo
! and plot
  OPEN(unit=2, file='output/global.dat', form='formatted')
  WRITE(2,*) nbgr
  WRITE(2,*) plot
  print*,'writing output/global.dat'
  CLOSE(unit=2)

  STOP
  
CONTAINS
  SUBROUTINE syminv(a, info)
    IMPLICIT NONE
    
    REAL a(:, :)
    INTEGER info ! status return
    ! local variables
    INTEGER n ! dimension
    INTEGER i,j ! index variables
    REAL, DIMENSION(:), ALLOCATABLE :: work
    
    INTEGER, DIMENSION(:), ALLOCATABLE :: iwork,ipiv
    
    REAL anorm ! 1-norm of A from slansy
    REAL rcond ! reciprocal condition number
    REAL slansy ! anorm function
    n = SIZE(a, 1)
    ALLOCATE(work(n*n),ipiv(n*n),iwork(n*n))
    
    ! routine for inverting a real symmetric positive definite matrix
    ! e.g. a covariance matrix (I hope)
    
    CALL dsytrf ('u', n, A, n, IPIV, WORK, n*n, info)
    CALL dsytri ('u', n, a, n, IPIV, WORK, info)
    DO j =2,n
       DO i=1,j
          a(j,i) = a(i,j)
       END DO
    END DO
    RETURN
    
  END SUBROUTINE syminv
  
END PROGRAM bsens
